#!/bin/sh

cd $HOME/notes

script_timeout=20

# fork code block that will wait and kill this shell if sleep timer finishesl
{
    sleep $script_timeout
    # kill the process group to ensure fzf is terminated
    kill -TERM 0 2>/dev/null
} &
timeout_pid=$!

# exec replaces current shell so previous fork will kill *this* shell if sleep timer finishes
exec sh -c '
    choice="$(fd . | fzf | sed 's/\.md$//')"
    kill '$timeout_pid' 2>/dev/null
    termux-open "$choice.md"
'
